store/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.store, name='store'), 
    path('search/', views.search, name='search'), 
    path('submit-review/<int:product_pk>/', views.submit_review, name='submit_review'), 
    path('<slug:category_slug>/', views.store, name='products_by_category'), 
    path('<slug:category>/<slug:product>/', views.product_detail, name='product_detail'), 
]

store/models.py
from django.db import models
from django.db.models import Avg, Count
from django.urls import reverse

from accounts.models import Account
from category.models import Category

# Create your models here.

class Product(models.Model):
    product_name    = models.CharField(max_length=200, unique=True)
    slug            = models.SlugField(max_length=200, unique=True)
    description     = models.TextField(max_length=500, blank=True)
    price           = models.FloatField()
    images          = models.ImageField(upload_to='photos/products')
    stock           = models.IntegerField()
    is_available    = models.BooleanField(default=True)
    category        = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    created_date    = models.DateTimeField(auto_now_add=True)
    modified_date   = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-modified_date',)

    def __str__(self):
        return self.product_name
    
    def get_absolute_url(self):
        return reverse('product_detail', args=[self.category.slug, self.slug])


    def averageReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
        avg = 0
        if reviews['average'] is not None:
            avg = float(reviews['average'])
        return avg

    def countReview(self):
        return ReviewRating.objects.filter(product=self, status=True).count()


from django.db.models.signals import pre_save
def price_rounder(sender, instance, **kwargs):
    instance.price = float(round(instance.price), 2)

# pre_save.connect(price_rounder, sender=Product)


class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(variation_category='c', is_active=True)

    def sizes(self):
        return super(VariationManager, self).filter(variation_category='s', is_active=True)


VARIATION_CATEGORIES = (
    ('c', 'color'), 
    ('s', 'size'), 
)


class Variation(models.Model):
    product      = models.ForeignKey(Product, related_name='variations', on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=1, choices=VARIATION_CATEGORIES)
    variation_value = models.CharField(max_length=60)
    is_active       = models.BooleanField(default=True)
    created_date    = models.DateTimeField(auto_now_add=True)
    modified_date   = models.DateTimeField(auto_now=True)
    
    objects = VariationManager()

    def __str__(self) -> str:
        return self.variation_value


class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject
    
    class Meta:
        ordering = ('-updated_at',)


class ProductGallery(models.Model):
    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE, blank=True, null=True)
    image = models.ImageField(upload_to='store/products/', max_length=255)

    def __str__(self) -> str:
        return self.product.product_name

    class Meta:
        verbose_name_plural = 'product gallery'

store/templates/store/product-detail.html
{% extends 'base.html' %}
{% load static %}

{% block jQuery %}
    $('.thumb a').click(function(e){
      e.preventDefault();
      $('.mainImage img').attr('src', $(this).attr("href"));
    })
{% endblock jQuery %}

{% block content %}
{% include 'includes/header.html' %}

<section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->
<div class="card">
	<div class="row no-gutters">
		<aside class="col-md-6">
      <article class="gallery-wrap">
        <div class="img-big-wrap mainImage" style="text-align: center;">
          <img src="{{ product.images.url }}">
        </div> <!-- img-big-wrap.// -->

      </article> <!-- gallery-wrap .end// -->
      <ul class="thumb">
        <li>
          <a href="{{ product.images.url }}" target="mainImage"><img src="{{ product.images.url }}" alt="Product Image"></a>
          {% for i in product_gallery %}
          <a href="{{i.image.url}}" target="mainImage"><img src="{{i.image.url}}" alt="Product Image"></a>
          {% endfor %}
        </li>
      </ul>
    </aside>

		<!-- product-info-aside -->
		<main class="col-md-6 border-left">
<article class="content-body">

<h2 class="title">{{ product.product_name }}</h2>
<div class="rating-star">
  <span>{{ average | safe }}</span> 
  <span>{{reviews.count}} review{{reviews.count|pluralize}}</span>
</div>

<div class="mb-3"> 
	<var class="price h4">${{ product.price|floatformat:2 }}</var> 
</div> <p>{{ product.description }}</p>

<hr>
	<form action="{% url 'add_cart' product.id %}" method="post">
    {% csrf_token %}
    <div class="row"><!-- Color -->
      <div class="item-option-select">
        <h6>Choose Color</h6>
        <div class="btn-group btn-group-sm btn-group-toggle" data-toggle="buttons">
          <div class="d-flex flex-wrap">
          {% for variation in product.variations.colors %}
          <label class="btn btn-light btn-check flex-fill" for="{{ variation.get_variation_category_display }}-{{ forloop.counter }}">
            <input type="radio" required name="radio_color" value="{{ variation.variation_value | lower }}" id="{{ variation.get_variation_category_display }}-{{ forloop.counter }}"> 
            {{ variation.variation_value | capfirst }}
          </label>
          {% endfor %}
          </div>
        </div> 
      </div>
    </div> <!-- row.// -->


    <div class="row"><!-- Size -->
      <div class="item-option-select">
        <h6>Select Size</h6>
        <div class="btn-group btn-group-sm btn-group-toggle" data-toggle="buttons">
          <div class="d-flex flex-wrap">
            {% for variation in product.variations.sizes %}
            <label class="btn btn-light btn-check flex-fill" for="{{ variation.get_variation_category_display }}-{{ forloop.counter }}">
              <input type="radio" required name="radio_size" value="{{ variation.variation_value | lower }}" id="{{ variation.get_variation_category_display }}-{{ forloop.counter }}"> 
              {{ variation.variation_value | upper }}
            </label>
            {% endfor %}
          </div>
          
        </div> 
      </div>
    </div> <!-- row.// -->

    
    <div class="row"><!-- Quantity -->
      <div class="item-option-select">
        <label for="quantity" class="form-label">
          <h6>Select quantity (between 1 and 5):</h6></label>
        <input type="number" required id="quantity" name="quantity" min="1" max="5"  value="1" class="form-control" >
      </div>
    </div> <!-- row.// -->

    <hr>
    {% if product.stock > 0 %}
      <button type="submit" class="btn  btn-primary"> <span class="text">Add to cart</span> <i class="fas fa-shopping-cart"></i>  </button>
      {% if in_cart or user_cart %}<div class="btn btn-success"><span class="text">Added to cart</span> <i class="fas fa-check"></i>  </div>
        <a href="{% url 'remove_cart' product.id %}?remove=All" class="btn btn-danger">Remove all</a>
      {% endif %}
    {% else %}
    <button class="btn  btn-secondary" disabled> <span class="text">Add to cart</span> <i class="fas fa-shopping-cart"></i>  </button>
    <h5 class="text-danger">Out of stock</h5>
    {% endif %}
	</form>
</article> <!-- product-info-aside .// -->

		</main> <!-- col.// -->
	</div> <!-- row.// -->
</div> <!-- card.// -->
<!-- ============================ COMPONENT 1 END .// ================================= -->

<!-- ============================ Customer Reviews ============================ -->
<br>
<div class="row">
	<div class="col-md-9">

    <header class="section-heading">
      <h3>Customer Reviews </h3>
    </header>

    {% if orderproduct %}
    <form action="{% url 'submit_review' product.pk %}" method="post">
      {% csrf_token %}
      <h5>Leave Your review</h5>
      <div class="mb-3">
        <!-- Rating stars -->
        <label>How do you rate this product?</label>

<br>
        <div class="rate mb-3">
          <input type="radio" name="rating" id="rating10" value="5" required checked/><label for="rating10" title="5"></label>
          <input type="radio" name="rating" id="rating9" value="4.5" required /><label for="rating9" title="4.5" class="half"></label>
          <input type="radio" name="rating" id="rating8" value="4" required /><label for="rating8" title="4"></label>
          <input type="radio" name="rating" id="rating7" value="3.5" required /><label for="rating7" title="3.5" class="half"></label>
          <input type="radio" name="rating" id="rating6" value="3" required /><label for="rating6" title="3"></label>
          <input type="radio" name="rating" id="rating5" value="2.5" required /><label for="rating5" title="2.5" class="half"></label>
          <input type="radio" name="rating" id="rating4" value="2" required /><label for="rating4" title="2"></label>
          <input type="radio" name="rating" id="rating3" value="1.5" required /><label for="rating3" title="1.5" class="half"></label>
          <input type="radio" name="rating" id="rating2" value="1" required /><label for="rating2" title="1"></label>
          <input type="radio" name="rating" id="rating1" value="0.5" required /><label for="rating1" title="0.5" class="half"></label>
        </div>

        <p>Review Title: </p> 
        {{ form.subject }}
        <p>Review: </p>
        {{ form.review }}
        <input type="submit" value="Submit Review" class="btn btn-success form-control">
      </div>
    </form>
    {% elif user.is_authenticated %}
      <p class="mb-4">You must purchase this product to post a review.</p>
    {% else %}
      <p class="mb-4">You must be logged in to leave a review. <span><a href="{% url 'user_login' %}?next={{ request.path }}">Login now</a></span></p>
    {% endif %}

    {% for review in reviews %}
    <article class="box mb-3">
      <div class="icontext w-100">
	{% if review.user.userprofile and review.user.userprofile.profile_picture %}
          <img src="{{review.user.userprofile.profile_picture.url}}" alt="Profile Picture" class="img-xs icon rounded-circle">
        {% else %}
          <img src={% static 'images/avatars/userprofile.png' %} class="img-xs icon rounded-circle">
        {% endif %}
	<div class="text">
          <span class="date text-muted float-md-right">{{ review.updated_at|timesince }} ago</span>  
          <h6 class="mb-1">{{ review.user.full_name }}</h6><p>{{ review.rating }} star rating</p>
          <div class="rating-star"><span>{{ review.stars | safe }}</span></div>
        </div>
      </div> <!-- icontext.// -->
      <div class="mt-3">
        <span class="date text-muted float-md-right">{{ review.updated_at|date }}</span>  
        <h6>{{ review.subject }}</h6>
        <p>
          {{ review.review }}<br>
          {% lorem 1 %}
        </p>	
      </div>
    </article>
    {% empty %}
    <article class="box mb-3">
      <div class="mt-3">
        <h6>Be first to review {{ product.product_name }}.</h6>
      </div>
    </article>
    {% endfor %}

	

	</div> <!-- col.// -->
</div> <!-- row.// -->


</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% include 'includes/footer.html' %}
{% endblock content %}

store/templates/store/store.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'includes/header.html' %}

<!-- ========================= SECTION PAGETOP ========================= -->
<section class="section-pagetop bg">
        <div class="container">
                <h2 class="title-page">Our Store
                        {% if category_name %} - {{ category_name }} 
                                {% if 'search/' in request.path and request.GET.keyword %}
                                for "{{ request.GET.keyword }}"
                                {% endif %}
                        {% endif %}
                </h2>
                
        </div> <!-- container //  -->
</section>
        <!-- ========================= SECTION PAGETOP END// ========================= -->
        
        <!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">
    <div class="container">
        
        <div class="row">
                <aside class="col-md-3">
                        
                        <div class="card">
                                <article class="filter-group">
                                        <header class="card-header">
                                                <a href="#" data-toggle="collapse" data-target="#collapse_1" aria-expanded="true" class="">
                                                        <i class="icon-control fa fa-chevron-down"></i>
                                                        <h6 class="title">Categories</h6>
                                                </a>
                                        </header>
                                        <div class="filter-content collapse show" id="collapse_1" style="">
                                                <div class="card-body">
                                                  <ul class="list-menu">
                                                    <li><a href="{% url 'store' %}">All products</a></li>
                                                    {% for category in links %}
                                                      <li><a href="{{ category.get_absolute_url }}">{{ category.category_name }} 
                                                        <span class="float-md-right">{{ category.products.count }}</span>
                                                      </a></li>
                                                    {% endfor %}
                                                  </ul>
                                                </div> <!-- card-body.// -->
                                        </div>
                                </article> <!-- filter-group  .// -->
                                <article class="filter-group">
                                        <header class="card-header">
                                                <a href="#" data-toggle="collapse" data-target="#collapse_4" aria-expanded="true" class="">
                                                        <i class="icon-control fa fa-chevron-down"></i>
                                                        <h6 class="title">Sizes </h6>
                                                </a>
                                        </header>
                                        <div class="filter-content collapse show" id="collapse_4" style="">
                                                <div class="card-body">
                                                <label class="checkbox-btn">
                                                <input type="checkbox">
                                                <span class="btn btn-light"> XS </span>
                                                </label>
                        
                                                <label class="checkbox-btn">
                                                <input type="checkbox">
                                                <span class="btn btn-light"> SM </span>
                                                </label>
                        
                                                <label class="checkbox-btn">
                                                <input type="checkbox">
                                                <span class="btn btn-light"> LG </span>
                                                </label>
                        
                                                <label class="checkbox-btn">
                                                <input type="checkbox">
                                                <span class="btn btn-light"> XXL </span>
                                                </label>
                                        </div><!-- card-body.// -->
                                        </div>
                                </article> <!-- filter-group .// -->
                                
                                <article class="filter-group">
                                        <header class="card-header">
                                                <a href="#" data-toggle="collapse" data-target="#collapse_3" aria-expanded="true" class="">
                                                        <i class="icon-control fa fa-chevron-down"></i>
                                                        <h6 class="title">Price range </h6>
                                                </a>
                                        </header>
                                        <div class="filter-content collapse show" id="collapse_3" style="">
                                                <div class="card-body">
                                                        
                                                        <div class="form-row">
                                                        <div class="form-group col-md-6">
                                                        <label>Min</label>
                                                        <!-- <input class="form-control" placeholder="$0" type="number"> -->
                                                                <select class="mr-2 form-control">
                                                                        <option value="0">$0</option>
                                                                        <option value="50">$50</option>
                                                                        <option value="100">$100</option>
                                                                        <option value="150">$150</option>
                                                                        <option value="200">$200</option>
                                                                        <option value="500">$500</option>
                                                                        <option value="1000">$1000</option>
                                                                </select>
                                                        </div>
                                                        <div class="form-group text-right col-md-6">
                                                        <label>Max</label>
                                                                <select class="mr-2 form-control">
                                                                        <option value="50">$50</option>
                                                                        <option value="100">$100</option>
                                                                        <option value="150">$150</option>
                                                                        <option value="200">$200</option>
                                                                        <option value="500">$500</option>
                                                                        <option value="1000">$1000</option>
                                                                        <option value="2000">$2000+</option>
                                                                </select>
                                                        </div>
                                                        </div> <!-- form-row.// -->
                                                        <button class="btn btn-block btn-primary">Apply</button>
                                                </div><!-- card-body.// -->
                                        </div>
                                </article> <!-- filter-group .// -->
                                
                        </div> <!-- card.// -->
        
                </aside> <!-- col.// -->




    <main class="col-md-9">
        <!-- sect-heading -->
        <header class="border-bottom mb-4 pb-3">
                {% include 'includes/alerts.html' %}
                        <div class="form-inline">
                                <span class="mr-md-auto">{{ product_count }} Item{{ product_count | pluralize }} found </span>
                        </div>
        </header>
        
        <!-- product details handling -->
        <div class="row">
        {% for product in products %}
                <div class="col-md-4">
                        <a href="{{ product.get_absolute_url }}" class="card-product">
                        <figure class="card card-product-grid">
                                <div class="img-wrap"> 
                                        <img src="{{ product.images.url }}">
                                </div> <!-- img-wrap.// -->
                                <figcaption class="info-wrap">
                                        <div class="fix-height">
                                                <span class="title">{{ product.product_name }}</span>
                                                <div class="price-wrap mt-2">
                                                        <span class="price">${{ product.price|floatformat:2 }}</span>
                                                </div> <!-- price-wrap.// -->
                                        </div>
                                        
                                        {% if product.pk in added_products %}
                                        <div class="btn btn-block btn-success"><span class="text">Added to cart</span> <i class="fas fa-check"></i>  </div>
                                        {% elif product.stock > 0 %}
                                        <a href="{% url 'add_cart' product.id %}" class="btn btn-block btn-primary">Add 1 to cart </a>
                                        {% else %}
                                        <button class="btn btn-block btn-secondary" disabled> <span class="text">Out of stock</span></button>
                                        {% endif %}
                                        	
                                </figcaption>
                        </a></figure>
                </div> <!-- col.// -->
        {% empty %}
        		<h2>No products found. Please try again later. </h2>
        {% endfor %}
        </div> <!-- row end.// -->

        <!-- Page navigation     -->
        {% if products.has_other_pages %}
        <nav class="mt-4" aria-label="Page navigation sample">
          <ul class="pagination">
            {% if products.number == 2 %}
              <li class="page-item"><a class="page-link" href=".{% if keyword %}?keyword={{ keyword }}{% endif %}">Previous</a></li>
            {% elif products.has_previous %}
              <li class="page-item"><a class="page-link" href="?page={{ products.previous_page_number }}{% if keyword %}&keyword={{ keyword }}{% endif %}">Previous</a></li>
            {% else %}
              <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
            {% endif %}

            {% for i in products.paginator.page_range %}
                {% if i == products.number %}
                    <li class="page-item active"><a class="page-link" href="#">{{ i }}</a></li>
                {% elif i == 1 %}
                    <li class="page-item"><a class="page-link" href=".{% if keyword %}?keyword={{ keyword }}{% endif %}">{{ i }}</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ i }}{% if keyword %}&keyword={{ keyword }}{% endif %}">{{ i }}</a></li>
                {% endif %}            
            {% endfor %}
            
            {% if products.has_next %}
              <li class="page-item"><a class="page-link" href="?page={{ products.next_page_number }}{% if keyword %}&keyword={{ keyword }}{% endif %}">Next</a></li>
            {% else %}
              <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
            {% endif %}
          </ul>
        </nav>
        {% endif %}
    </main> <!-- col.// -->
        
        </div>
        
    </div> <!-- container .//  -->
</section>
        <!-- ========================= SECTION CONTENT END// ========================= -->

{% include 'includes/footer.html' %}
{% endblock content %}